### ISSUE TITLE
While still on an inspector focused field hitting "backspace" deletes a node instead

### ISSUE THREAD

**Issue by passiomatic** [passiomatic/elm-designer#24]
Steps to reproduce:

- Drag a button on the page
- Focus the horizontal position field
- Enter a number, e.g. 10, press `enter` key
- The button moves 10 to the right
- The focus is still on the horizontal position field
- Press `backspace` key to remove the `0` from the `10`

The focus needs to be reset after hitting the `enter` key. I need to investigate on why this is not the case. 

This is most likely linked to #7.

**Comment by magopian** [comment]
I fiddled a bit with the code, and it seems that if we could NOT set `inspector = NotEdited` [here](https://github.com/passiomatic/elm-designer/blob/92b9edd4e15ac1a4cc704d41bfd24f143d0666a2/src/Main.elm#L864) on inputs that allow for text editing (like the label, the positions etc...), it would do the trick.

But there might be other consequences to not set that, so I'm not sure it's the way to go.

If you tell me it is, I might add a new `applyChangeAndFinishAndKeepFocus` helper that does the same thing, but doesn't set the `inspector` key ;) Let me know!

**Comment by passiomatic** [comment]
Yes, it is that `inspector = NotEdited` in `applyChangeAndFinish` which ends the editing mode, but some time ago  I also removed the `unfocusElement` from the code - probably after a refactor - hence it is obvious to me now that Elm cannot remove the field focus when editing operation is finished. 

So my point is: should we hit `enter` key, finish editing and unfocus element - effectively fixing the bug - or is there some value on commit the change but continuing to stay in editing mode with the focus on the _same_ field?

**Comment by magopian** [comment]
Well in my case I was testing the value: changing it slightly, pressing `enter` to see how it looked, then modifying it again... to me at least it felt natural.
Maybe elm could focus another element (the node being modified?) after each `applyChangeAndFinish`, but i'm not sure what value it would give? Also it would mean that going from one field to the other wouldn't be possible anymore, as the focus would jump away?

**Comment by passiomatic** [comment]
> Well in my case I was testing the value: changing it slightly, pressing enter to see how it looked, then modifying it again... to me at least it felt natural.

Yes, this is the way to go. It is the expected behavior for most of us.
