### ISSUE TITLE
Can't remove Label on text fields

### ISSUE THREAD

**Issue by CharlonTank** [passiomatic/elm-designer#25]
When I remove a label, it either remove the text field or it resets to "Label"

**Comment by passiomatic** [comment]
The code that applies the label is here https://github.com/passiomatic/elm-designer/blob/master/src/Document.elm#L746. 

More generally, we need to expose the `LabelData.position` setting (perhaps via a `select`) so we can tell Elm UI more explicitly that we don't want the label to be visible (see: https://package.elm-lang.org/packages/mdgriffith/elm-ui/latest/Element-Input#labelHidden)
