### ISSUE TITLE
Segfault when running with appimage-run on NixOS (regression from 0.2.0 to 0.2.1)

### ISSUE THREAD

**Issue by Zimmi48** [passiomatic/elm-designer#26]
I'm not sure if this issue is specific to my non-standard system or not.

I'm on NixOS, a Linux distribution that does not follow standard FHS conventions. AppImages are not completely portable on this system but a tool called `appimage-run` is provided.

Running `appimage-run ElmDesigner-0.2.0-linux.AppImage` works. It correctly opens the GUI and echoes the following in the console:

```
Uncompress ElmDesigner-0.2.0-linux.AppImage of type 02 @ offset 188392
[=================================================================================================================================================================================================-] 2930/2930 100%
ElmDesigner-0.2.0-linux.AppImage is now installed in /home/theo/.cache/appimage-run/4c97e0aae6d9c722d07a00e4af6318536b8f9bd26e26682e2c13fd8cf605a0c2
(node:4997) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
```

On the contrary, calling `appimage-run ElmDesigner-0.2.1-linux.AppImage` does not work. It exits with error code 139, printing the following in the console (no GUI is opened at all):
```
ElmDesigner-0.2.1-linux.AppImage installed in /home/theo/.cache/appimage-run/b34818eed209fd01ac2eed62afc6b9f15fd1bb3b26040799093c1c6b0f74cd46
Segmentation fault (core dumped)
```

**Comment by passiomatic** [comment]
Thanks for the report. I can successfully run the AppImage file on latest Ubuntu here so is hard to tell what's going on with NixOS.

**Comment by Zimmi48** [comment]
Indeed. If you give me specific debug instructions, I can apply them for you. Otherwise, this is also fine to close this as a "won't fix".

**Comment by passiomatic** [comment]
I do some googling and found several people having issues running Electron apps on NixOS. It seems tricky to get it right. I wii leave it open with a help wanted label. Maybe someone can give us some hints.

**Comment by Zimmi48** [comment]
FTR this works again with the latest release (0.3.0).
