### ISSUE TITLE
Implement border style switcher in inspector

### ISSUE THREAD

**Issue by passiomatic** [passiomatic/elm-designer#3]
We miss the ability to specify a border style for every element (https://package.elm-lang.org/packages/mdgriffith/elm-ui/latest/Element-Border#solid). 

So let's add a new button group switcher (https://getbootstrap.com/docs/4.5/components/button-group/#basic-example) like the ones we have already, most likely positioned in the inspector between Border size and color, which sets `Node.borderStyle` property accordingly.  I would call the three border styles labels "Solid", "Dashed" and "Dotted".

To accomplish that a new `Msg` is needed, so `BorderStyleChanged BorderStyle` would do the trick.

**Comment by CharlonTank** [comment]
[WIP] - https://github.com/passiomatic/elm-designer/pull/18

**Comment by passiomatic** [comment]
I was thinking to add this via button switcher, not a `select` like I'm seeing from your PR. I'll take care of this.
