### ISSUE TITLE
Triple click needed to edit paragraph

### ISSUE THREAD

**Issue by MartinSStewart** [passiomatic/elm-designer#47]
After placing a paragraph element it says "Double click to edit" but only double clicking doesn't set focus to the text input region that becomes visible. Instead a third click is needed before the user can enter text in the paragraph.

**Comment by passiomatic** [comment]
I thought it was a FF issue, but strangely enough I cannot reproduce this on a Mac. 🤔

**Comment by MartinSStewart** [comment]
I'm unable to reproduce this issue on Windows now. I'm not what exactly triggered it but I'll close this issue and make a new issue with more details if I run into this bug again.
